In [2]:
#CARGAMOS LIBRERIAS
import pandas as pd
import numpy as np

In [6]:
df_games=pd.read_csv('../fastapi/gamesNoGS.csv',parse_dates=['release_date'])
df_items=pd.read_csv('../fastapi/items.csv')
df_reviews=pd.read_csv('../fastapi/reviews_sentiment_analysis.csv')
df_genres=pd.read_csv('../fastapi/games_genres.csv')
df_specs=pd.read_csv('../fastapi/games_specs.csv')

In [77]:
df_items.head(2)

             user_id  item_id  playtime_forever
0  76561197970982479     10.0               6.0
1  76561197970982479     30.0               7.0

In [78]:
df_reviews.head(10)

             user_id  posted  item_id  recommend  sentiment_analysis
0  76561197970982479  2011.0     1250       True                   2
1  76561197970982479  2011.0    22200       True                   2
2  76561197970982479  2011.0    43110       True                   2
3            js41637  2014.0   251610       True                   2
4            js41637  2013.0   227300       True                   2
5            js41637  2013.0   239030       True                   2
6          evcentric  2015.0   370360       True                   2
7          evcentric  2014.0   237930       True                   2
8          evcentric  2014.0   263360       True                   1
9          evcentric  2014.0   107200       True                   2

In [5]:
df_genres.head(10)

,id,Indie,Action,Casual,Adventure,Strategy,Simulation,RPG,Free to Play,Early Access,Sports,Massively Multiplayer,Racing,Utilities
0,761140,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,643980,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
2,670290,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,767400,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,772540,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,774276,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
6,774277,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
7,774278,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
8,768800,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,768570,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [7]:
df_specs.head(10)

,id,Single-player,Steam Achievements,Downloadable Content,Steam Trading Cards,Steam Cloud,Multi-player,Full controller support,Partial Controller Support,Steam Leaderboards,Co-op,Shared/Split Screen,Cross-Platform Multiplayer,Stats,Online Multi-Player
0,761140,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,643980,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,670290,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,767400,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,772540,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,774276,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
6,774277,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
7,774278,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
8,768800,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
9,768570,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
# def PlayTimeGenre( genero : str ): #Debe devolver año con mas horas jugadas para dicho género.
#Ejemplo de retorno: {"Año de lanzamiento con más horas jugadas para Género X" : 2013}
def PlayTimeGenre(genero: str):
    if genero not in df_genres.columns:
        return 'Invalid Genre'
    # Realizar un inner join entre df_genres y df_items usando 'id' como clave
    merged_df = df_genres.merge(df_items, left_on='id', right_on='item_id', how='inner')
    
    # Filtrar por el género deseado
    filtered_df = merged_df[merged_df[genero] == 1]
    
    # Realizar otro inner join con df_games usando 'id' como clave
    final_df = filtered_df.merge(df_games, on='id', how='inner')

    # Calcular la suma de las horas jugadas por año
    playtime_by_year = final_df.groupby(final_df['release_date'].dt.year)['playtime_forever'].sum()
    
    # Encontrar el año con más horas jugadas
    year_with_most_playtime = playtime_by_year.idxmax().item()  # Convierte a tipo de dato nativo
    
    return year_with_most_playtime

In [71]:

genero_deseado = 'Adventure'
year = PlayTimeGenre(genero_deseado)
print(f"Año de lanzamiento con más horas jugadas para Género '{genero_deseado}' : {year}")

Año de lanzamiento con más horas jugadas para Género 'Adventure' : 2011

In [74]:
#def UserForGenre( genero : str ): 
#Debe devolver el usuario que acumula más horas jugadas para el género dado 
#y una lista de la acumulación de horas jugadas por año.
#Ejemplo de retorno: 
#           {"Usuario con más horas jugadas para Género X" : us213ndjss09sdf,
#            "Horas jugadas":[
#                   {Año: 2013, Horas: 203}, 
#                   {Año: 2012, Horas: 100}, 
#                   {Año: 2011, Horas: 23}
#                   ]}
def UserForGenre(genero: str):
    if genero not in df_genres.columns:
        return None

    # Realizar un inner join entre df_genres y df_items usando 'id' como clave
    merged_df = df_genres.merge(df_items, left_on='id', right_on='item_id', how='inner')

    # Filtrar por el género deseado
    filtered_df = merged_df[merged_df[genero] == 1]

    # Realizar otro inner join con df_games usando 'id' como clave
    final_df = filtered_df.merge(df_games, on='id', how='inner')

    # Calcular la suma de las horas jugadas por usuario y año
    user_year_playtime = final_df.groupby(['user_id', final_df['release_date'].dt.year])['playtime_forever'].sum().reset_index()

    # Excluir el año 1900 de la suma de horas jugadas
    user_year_playtime = user_year_playtime[user_year_playtime['release_date'] != 1900]

    # Encontrar el usuario con más horas jugadas para el género
    user_with_most_playtime = user_year_playtime.groupby('user_id')['playtime_forever'].sum().idxmax()

    # Filtrar los datos del usuario con más horas jugadas
    user_most_playtime_data = user_year_playtime[user_year_playtime['user_id'] == user_with_most_playtime]

    # Crear una lista de acumulación de horas jugadas por año
    hours_played_by_year = [{'Año': year, 'Horas': playtime} for year, playtime in zip(user_most_playtime_data['release_date'], user_most_playtime_data['playtime_forever'])]

    # Devolver el resultado como un diccionario
    result = {
        f"Usuario con más horas jugadas para Género {genero}": user_with_most_playtime,
        "Horas jugadas": hours_played_by_year
    }

    return result

In [75]:

genero_deseado = 'Action'
result = UserForGenre(genero_deseado)
result

{'Usuario con más horas jugadas para Género Action': 'DeEggMeister',
 'Horas jugadas': [{'Año': 1994, 'Horas': 20.0},
  {'Año': 1995, 'Horas': 80.0},
  {'Año': 1998, 'Horas': 1504.0},
  {'Año': 1999, 'Horas': 993.0},
  {'Año': 2000, 'Horas': 7276.0},
  {'Año': 2001, 'Horas': 295.0},
  {'Año': 2002, 'Horas': 1388.0},
  {'Año': 2003, 'Horas': 4608.0},
  {'Año': 2004, 'Horas': 64061.0},
  {'Año': 2005, 'Horas': 8908.0},
  {'Año': 2006, 'Horas': 16235.0},
  {'Año': 2007, 'Horas': 22869.0},
  {'Año': 2008, 'Horas': 99995.0},
  {'Año': 2009, 'Horas': 207187.0},
  {'Año': 2010, 'Horas': 139111.0},
  {'Año': 2011, 'Horas': 337126.0},
  {'Año': 2012, 'Horas': 1182929.0},
  {'Año': 2013, 'Horas': 460357.0},
  {'Año': 2014, 'Horas': 192694.0},
  {'Año': 2015, 'Horas': 274834.0},
  {'Año': 2016, 'Horas': 111759.0},
  {'Año': 2017, 'Horas': 87183.0}]}

In [98]:
def UsersRecommend(anio: int):
    if anio not in df_reviews['posted'].values:
        no_anio = ['No hay reviews del año solicitado']
        return no_anio
    # Filtrar las revisiones que cumplen con los criterios de recomendación y análisis de sentimientos
    filtered_reviews = df_reviews[(df_reviews['recommend'] == True) & (df_reviews['sentiment_analysis'] <= 1)]

    # Realizar un inner join entre las revisiones y los juegos usando 'item_id' como clave
    merged_df = filtered_reviews.merge(df_games, left_on='item_id', right_on='id', how='inner')

    # Filtrar los juegos que tienen el anio deseado
    filtered_games = merged_df[merged_df['posted'] == anio]

    # Calcular la popularidad de los juegos en función de la cantidad de recomendaciones
    game_popularity = filtered_games.groupby('app_name')['recommend'].sum().reset_index()

    # Ordenar los juegos por popularidad en orden descendente
    top_games = game_popularity.sort_values(by='recommend', ascending=False).head(3)

    # Crear la lista de juegos recomendados en el formato deseado
    recommended_games = [{"Puesto {}: {}".format(index + 1, game)} for index, game in enumerate(top_games['app_name'])]

    return recommended_games

In [99]:

año_deseado = 2018
result = UsersRecommend(año_deseado)
print(result)

['No hay reviews del año solicitado']

In [103]:
#def UsersNotRecommend( año : int ): Devuelve el top 3 de juegos MENOS recomendados por usuarios para el año dado. (reviews.recommend = False y comentarios negativos)
#Ejemplo de retorno: [{"Puesto 1" : X}, {"Puesto 2" : Y},{"Puesto 3" : Z}]

def UsersNotRecommend(anio: int):
    if anio not in df_reviews['posted'].values:
        no_anio = ['No hay reviews del año solicitado']
        return no_anio
    # Filtrar las revisiones que cumplen con los criterios de recomendación y análisis de sentimientos
    filtered_reviews = df_reviews[(df_reviews['recommend'] == False) & (df_reviews['sentiment_analysis'] == 0)]

    # Realizar un inner join entre las revisiones y los juegos usando 'item_id' como clave
    merged_df = filtered_reviews.merge(df_games, left_on='item_id', right_on='id', how='inner')

    # Filtrar los juegos que tienen el anio deseado
    filtered_games = merged_df[merged_df['posted'] == anio]

    # Calcular la popularidad de los juegos en función de la cantidad de recomendaciones
    game_popularity = filtered_games.groupby('app_name')['recommend'].sum().reset_index()

    # Ordenar los juegos por popularidad en orden descendente
    top_games = game_popularity.sort_values(by='recommend', ascending=False).head(3)

    # Crear la lista de juegos recomendados en el formato deseado
    recommended_games = [{"Puesto {}: {}".format(index + 1, game)} for index, game in enumerate(top_games['app_name'])]

    return recommended_games

In [104]:

año_deseado = 2014
result = UsersNotRecommend(año_deseado)
print(result)

[{'Puesto 1: 8BitMMO'}, {'Puesto 2: R.A.W. Realms of Ancient War'}, {'Puesto 3: Sacred 3'}]

In [105]:
#def sentiment_analysis( año : int ): Según el año de lanzamiento, se devuelve una lista con la cantidad de registros de reseñas de usuarios que se encuentren categorizados con un análisis de sentimiento.
#Ejemplo de retorno: {Negative = 182, Neutral = 120, Positive = 278}


def sentiment_analysis(año: int):
    # Filtrar los juegos del año deseado en df_games
    filtered_games = df_games[df_games['release_date'].dt.year == año]

    # Obtener los ID de los juegos del año deseado
    juegos_del_año = filtered_games['id'].tolist()

    # Filtrar las revisiones de los juegos del año deseado en df_reviews
    filtered_reviews = df_reviews[df_reviews['item_id'].isin(juegos_del_año)]

    # Contar la cantidad de registros de reseñas por análisis de sentimiento
    sentiment_counts = filtered_reviews['sentiment_analysis'].value_counts()

    # Crear el diccionario de retorno en el formato deseado
    result = {
        'Negative': sentiment_counts.get(0, 0),
        'Neutral': sentiment_counts.get(1, 0),
        'Positive': sentiment_counts.get(2, 0)
    }

    return result

In [109]:
año_deseado = 2017
result = sentiment_analysis(año_deseado)
print(result)

{'Negative': 260, 'Neutral': 336, 'Positive': 1006}